name: Build

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions: read-all 
jobs:
  webhook:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
    - name: Trigger Build Webhook
      run: |
          URL="${{ secrets.NECTO_BUILD_WEBHOOK }}"
          curl -X POST -d {} "$URL" -H "Content-Type: application/json"
