name: Markdown Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@main
    - uses: DavidAnson/markdownlint-cli2-action@v16
      with:
        config: './.markdownlint.json'
        globs: '**/*.md'
