name: Release

on:
  release:
    types: [published]

permissions: read-all 
jobs:
  webhook:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
    - name: Trigger Build Webhook
      run: |
          URL="${{ secrets.AMPLIFY_BUILD_WEBHOOK }}"
          curl -X POST -d {} "$URL" -H "Content-Type: application/json"
